#!/bin/bash
# Install AWS CodeStar remote access management.
# Allows project members to remotely access Amazon EC2 instances running Linux associated with the project.
wget -O /usr/local/bin/get_authorized_keys https://s3.amazonaws.com/awscodestar-remote-access-us-east-1/get_authorized_keys
chmod 755 /usr/local/bin/get_authorized_keys
sed -i '/AuthorizedKeysCommand /s/.*/AuthorizedKeysCommand \/usr\/local\/bin\/get_authorized_keys/g' /etc/ssh/sshd_config
sed -i '/AuthorizedKeysCommandUser /s/.*/AuthorizedKeysCommandUser root/g' /etc/ssh/sshd_config
/etc/init.d/sshd restart
yum update -y aws-cfn-bootstrap
yum install -y aws-cli
# Install pip and python dev libraries.
yum install -y python27-devel python27-pip gcc
# pip install boto3
# pip install pycrypto
